### ISSUE TITLE
コーポレイトサイトの目的

### ISSUE THREAD

**Issue by hirokiyamada-reno** [reno-shelter/corporate_site#1]
# Why

コーポレイトサイトを作成する際に、価値あるものにするため。

# What

コーポレイトサイトの目的の設定

# アウトプット

コーポレイトサイトの目的の言語化

**Comment by hirokiyamada-reno** [comment]
__コーポレイトの一般的な対象者__

上からRENOの優先順位

1. 採用希望者
2. 見込み顧客
3. 既存顧客
4. 株主やパートナー

* 株主が少ないため株主やパートナーは優先順位低い
* 既存顧客に対してのソリューションは多くないので、営業が伝えるだけで十分
* よって採用と見込み顧客が上位にくる。

つまり、基本的な目的は二つ。

*.採用の確度を上げる
→何をやっている会社なのかがわかり、それを面白そうと感じることができる

*新規顧客からの信頼獲得
→適切な情報が全てあり、我々のミッション・ビジョンがきちんと伝わる

__キーワードは「イケてる」と「ちゃんとしてる」__

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

新規顧客にたいして。
信頼獲得ということは、インバウンドで企業から問い合わせが来るような内容では無いという認識でいいですか？

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

コーポレイトサイトにインバウンドで来るフェーズではないと思うんだよね。
サービスサイトが拡散されて、そこから入った企業が、どんな会社？？って見て、なるほど。ちゃんとしてるじゃん→サービスに登録って流れかなと。基本的なサービスの説明はサービスサイトのほうが上手くできるはずだし。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

なるほど。そうすると目標は下記でいいと思います。

>*.採用の確度を上げる
>→何をやっている会社なのかがわかり、それを面白そうと感じることができる

>*新規顧客からの信頼獲得
>→適切な情報が全てあり、我々のミッション・ビジョンがきちんと伝わる

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 
おけ。ではこれで確定でクローズします。

**Comment by hirokiyamada-reno** [comment]
# 結論

### コーポレイトサイトの目的

* 採用の確度を上げる
→何をやっている会社なのかがわかり、それを面白そうと感じることができる

* 新規顧客からの信頼獲得
→適切な情報が全てあり、我々のミッション・ビジョンがきちんと伝わる

__キーワードは「イケてる」と「ちゃんとしてる」__
