### ISSUE TITLE
コーポレイトサイトのコンテンツ

### ISSUE THREAD

**Issue by hirokiyamada-reno** [reno-shelter/corporate_site#2]
# WHY

コーポレイトサイトの目的を的確に果たすコンテンツを用意するため

# WHAT

コーポレイトサイトのコンテンツを洗い出し、何を載せるかを決定する

# アウトプット

コンテンツの一覧表

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira @kokihori 

### コンテンツの洗い出し（一般論）
* 
* 
* 
* 
* 
* 
*

**Comment by hirokiyamada-reno** [comment]
他、追加できそうなものがあったら、書き出してー。洗い出し終わったら、選定していこう。

**Comment by kokihori** [comment]
@hirokiyamada-reno 
プライバシーポリシーと経営方針を追加しました。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno @kokihori 

以下追加。山田くんの上の投稿に追加しておきます。

__企業情報__
・個人情報保護方針

__サービス内容__
・取引先情報

__採用情報__
・仕事内容

__ブログ__
・会社ブログ
・採用ブログ
・エンジニアブログ

**Comment by hirokiyamada-reno** [comment]
@kokihori @ryotakodaira 

二人ともありがとう！！
かなり網羅的に出たと思う。

ここからは目的に対して必要なものを選定していく形だね。

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 
ミッション、ビジョン、経営理念は企業文化に含まれてますか？

選定方法はどうしましょう。
誰か1人が一通り案を出して、それに対して議論をしていく形にしますか？

**Comment by kokihori** [comment]
@hirokiyamada-reno @ryotakodaira 
とりあえず同じページにまとめられる項目を出していくのはどうです？
そしたら必然的に似た内容の項目がくっついていくのでその中から省略、統合できるのを議論していけばいいかも。

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

> ミッション、ビジョン、経営理念は企業文化に含まれてますか？

含まれてないね。
企業理念の中にミッション・ビジョン・理念は含めようか。
それと企業文化は別個で。

**Comment by hirokiyamada-reno** [comment]
@kokihori  @ryotakodaira 

> とりあえず同じページにまとめられる項目を出していくのはどうです？
そしたら必然的に似た内容の項目がくっついていくのでその中から省略、統合できるのを議論していけばいいかも。

方法はこれでいこう！！

**Comment by hirokiyamada-reno** [comment]
@kokihori @ryotakodaira 

とりあえず、明らかに今の時点ではいらない項目には×つけるね。

__企業情報__

会社概要
事業内容
社長挨拶
企業理念
企業文化
住所/お問い合わせ先
×CSR
プライバシーポリシー
個人情報保護方針

__ニュースリリース__
お知らせ
×新規取引情報

__サービス内容__
製品・サービス情報
×取引先情報

__採用情報__
会社について
求める人物像→wantedlyへの導線
募集要項
エントリーボタン→wantedlyボタン
×よくある質問
従業員インタビュー
仕事内容

__IR情報__
×IRカレンダー
×株式情報
×IRライブラリー
×コーポレートガバナンス
×有価証券報告書
×決算短信
×事業報告書
×経営方針

__ブログ__
会社ブログ
採用ブログ
エンジニアブログ

**Comment by kokihori** [comment]
@hirokiyamada-reno 
プライバシーポリシー＆個人情報保護方針
企業理念＆企業文化

この２つはまとめられませんかね？

**Comment by hirokiyamada-reno** [comment]
@kokihori 

> プライバシーポリシー＆個人情報保護方針
企業理念＆企業文化
この２つはまとめられませんかね？

まとめられるので、まとめようか。

**Comment by hirokiyamada-reno** [comment]
現状

__企業情報__
会社概要
事業内容
社長挨拶
企業理念&企業文化
住所/お問い合わせ先
プライバシーポリシー&個人情報保護方針

__ニュースリリース__
お知らせ

__サービス内容__
製品・サービス情報

__採用情報__
会社について
×求める人物像→wantedlyへの導線
募集要項
×エントリーボタン→wantedlyボタン
従業員インタビュー
仕事内容

__ブログ__
会社ブログ
採用ブログ
エンジニアブログ

**Comment by hirokiyamada-reno** [comment]
従業員インタビューもwantedlyに追加できるから、今は不要だね。

ブログはエンジニアブログ以外いる？？
運用する人間がいないから、更新止まる気がする。

**Comment by hirokiyamada-reno** [comment]
あと、事業内容は人材業界一本だし、サービスの内容みればそれはわかるから、今はいらないかな？

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 

>ブログはエンジニアブログ以外いる？？
>運用する人間がいないから、更新止まる気がする。

ですね。まずはエンジニアブログだけでいいかと。

>あと、事業内容は人材業界一本だし、サービスの内容みればそれはわかるから、今はいらないかな？

会社概要を表現するのに表を使用することになると思うので、その表の中の一行に事業内容について記載するだけでいいと思います。

**Comment by hirokiyamada-reno** [comment]
てことは、

__企業情報__
会社概要
社長挨拶
企業理念&企業文化
住所/お問い合わせ先
プライバシーポリシー&個人情報保護方針

__ニュースリリース__
お知らせ

__サービス内容__
製品・サービス情報

__採用情報__
会社について
×求める人物像→wantedlyへの導線
募集要項
×エントリーボタン→wantedlyボタン

__ブログ__
エンジニアブログ

**Comment by hirokiyamada-reno** [comment]
あとは、トップページになんのコンテンツを載せるかだね。

**Comment by kokihori** [comment]
@hirokiyamada-reno 
質問なんですが、ブログって単に社員ブログじゃダメなんですか？
タグとか執筆者とかカテゴリーとかで分けるのでもいいのでは？と思いました。
誰でもなんでも書き込んでいく方が負担も分散できるし、会社の雰囲気も分かるんじゃないかな。

**Comment by hirokiyamada-reno** [comment]
@kokihori 

ブログはエンジニアブログとその他には最低限分ける必要があるかなーとは思うんだよね。

エンジニアブログ（対エンジニアへのブランディング・交流が目的）の内容は、普通の読者には全く理解できない内容になるから、読者が相当限られてくる。逆に、エンジニア採用とかではこのツールが非常に有効になるんだけど。そういう意味でいうと、たしかにタグとかで分けることはできるんだけど、エンジニア向けだけは別枠にしておきたいんだよね。かつ、基本的に今後採用していきたいのは、エンジニアだから、エンジニアブログのみでもいいとは思う。

ただ、それ以外って形で、社員ブログを作るのは運用さえできればかなりアリだとは思うが、どこまで運用できるか。

**Comment by hirokiyamada-reno** [comment]
@kokihori  @ryotakodaira 

これはもうクローズしちゃっていいかな？

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno 
はい、大丈夫です。

**Comment by hirokiyamada-reno** [comment]
### 結論

__企業情報__

会社概要
社長挨拶
企業理念&企業文化
住所/お問い合わせ先
プライバシーポリシー&個人情報保護方針

__ニュースリリース__

お知らせ

__サービス内容__

製品・サービス情報

__採用情報__

会社について
募集要項
wantedlyへの誘導

__ブログ__
エンジニアブログ
