### ISSUE TITLE
ワイヤーフレームの修正

### ISSUE THREAD

**Issue by ryotakodaira** [reno-shelter/corporate_site#3]
# WHY

コーポレイトサイトの目的・キーワードにあったコンテンツ配置、デザインを実現するため。

# WHAT

細かいコンテンツの過不足の洗い出し、デザイン視点からの修正を行う。

# アウトプット

ワイヤーフレーム画像の更新。

**Comment by hirokiyamada-reno** [comment]
### 気になった点

* 新卒紹介について、コーポレートサイトに載せなくていいかも
→コーポレートサイトの目的に新規での営業の獲得はないしかつ、紹介のイメージと新サービスのイメージが全く違うのでブランディングに影響する可能性があるため

* お問い合わせのフォームがいろんな場所にあって、もうちょっと減らせるかも
→お問い合わせ自体が目的ではないから、うるさくなっちゃうのは、あまり良くないかと

* 企業情報のところは社長挨拶が一番上かなー。これは順番を要検討

**Comment by taronkjm** [comment]
新卒紹介をテレアポで取る際にhp見せながらってって可能性は残らない？

**Comment by hirokiyamada-reno** [comment]
@taronkjm @kikukawa-reno  @saki-ando @ryotakodaira 

> 新卒紹介をテレアポで取る際にhp見せながらってって可能性は残らない？

可能性はある。
なので、これは新卒紹介の説明を載せることによる__新規営業の獲得コストの低下__というメリットと、__ブランディングの統一性が失われる__というデメリットの比較で決めるべきだね。

メリットがどれだけあるのかは、実際にテレアポしている人の意見が欲しいね。これまでの姿を見てると、そこまで必要性は感じない（興味を持っている企業には全て資料の送付を行っているので）けど。

ブランディングに関しては、
* 人材業界に対して新しい解決策を提供している
* 技術で人材業界を変えようとしている
* イケてるサービスをやっている

ここらへんのイメージをつける際に、全く普通の新卒紹介を出すことは少なからず悪影響はあるかなとは思う。今のところは、新卒紹介をアプリを通して行うようになったら、載せるようにすればいいかなと思っている。

のが、俺と小平の意見だが、営業さんの意見も聞きたい。

**Comment by kikukawa-reno** [comment]
テレアポをしている中で、新卒紹介事業のモデルはどこも変わらないから、特にHPを見て理解して貰う必要性は非常に小さいと思います。

それよりも、会社としてのスタンスとか方向性の部分で興味を得ているほうが強いので、新卒紹介の説明は無くて問題ないかなと思います。

今まであった例でHPを見てくれたときとか、今後HPがあったら便利だなと思う部分は、信頼性をソーシャルで獲得することなのかなーと思います。
なので、短期的にも長期的にもブランディングメインのHPが欲しいと思います。

新卒紹介のアプリが実現した場合は、欲しいな！

**Comment by ryotakodaira** [comment]
@hirokiyamada-reno @kokihori 

ワイヤーフレームの修正版をアップしました。

## 変更点

* 新卒紹介サービスのページ削除
* 企業情報ページの内容をトップページに移動
* お問い合わせページ削除(お問い合わせフォームはトップページ下部のみ)
* 採用ページ作成

**Comment by hirokiyamada-reno** [comment]
@ryotakodaira 

完成したやつで、終了ならクローズさせちゃってー。
